"use strict";
const CLOUD_SYNC_CONFIG=Object.freeze({url:"https://iuhysaynjujihmnnapma.supabase.co",key:"sb_publishable_15zVMSb_3V8Ekch4L2_kLw_T-UjfV7x",stateId:"feuerwehr-wasser"});
let cloudSyncTimer=null,cloudSyncBusy=false,cloudSyncApplying=false,cloudLastUpdated="";
function cloudSession(){try{return JSON.parse(localStorage.getItem("fw_cloud_session")||"null");}catch{return null;}}
function saveCloudSession(value){if(value)localStorage.setItem("fw_cloud_session",JSON.stringify(value));else localStorage.removeItem("fw_cloud_session");}
function cloudHeaders(extra={}){const session=cloudSession();return {apikey:CLOUD_SYNC_CONFIG.key,Authorization:`Bearer ${session?.access_token||CLOUD_SYNC_CONFIG.key}`,"Content-Type":"application/json",...extra};}
function cloudStatus(text,state="idle"){const button=document.getElementById("cloudSyncButton"),label=document.getElementById("cloudSyncLabel");if(label)label.textContent=text;if(button){button.dataset.state=state;button.title=text;}}
function ensureCloudSyncUi(){if(document.getElementById("cloudSyncButton"))return;const button=document.createElement("button");button.id="cloudSyncButton";button.className="cloud-sync-button";button.type="button";button.innerHTML='<span aria-hidden="true">☁</span><b id="cloudSyncLabel">Cloud</b>';document.body.appendChild(button);const dialog=document.createElement("dialog");dialog.id="cloudSyncDialog";dialog.className="cloud-sync-dialog";dialog.innerHTML='<form method="dialog"><header><div><small>Geräteübergreifende Daten</small><h2>Cloud-Synchronisierung</h2></div><button value="cancel" aria-label="Schließen">×</button></header><div class="cloud-sync-body"><p id="cloudSyncMessage">Mit einem in Supabase angelegten Benutzer anmelden.</p><label>E-Mail<input id="cloudSyncEmail" type="email" autocomplete="username"></label><label>Passwort<input id="cloudSyncPassword" type="password" autocomplete="current-password"></label><div class="cloud-sync-actions"><button type="button" class="primary-button" id="cloudSyncLogin">Anmelden und synchronisieren</button><button type="button" class="outline-button" id="cloudSyncNow">Jetzt synchronisieren</button><button type="button" class="secondary-button" id="cloudSyncLogout">Cloud abmelden</button></div><p class="cloud-sync-detail" id="cloudSyncDetail"></p></div></form>';document.body.appendChild(dialog);button.onclick=()=>{renderCloudDialog();dialog.showModal();};dialog.querySelector("#cloudSyncLogin").onclick=cloudLogin;dialog.querySelector("#cloudSyncNow").onclick=()=>syncCloudState({manual:true});dialog.querySelector("#cloudSyncLogout").onclick=()=>{saveCloudSession(null);cloudStatus("Cloud abgemeldet","offline");renderCloudDialog();};}
function renderCloudDialog(){const session=cloudSession(),detail=document.getElementById("cloudSyncDetail"),login=document.getElementById("cloudSyncLogin"),now=document.getElementById("cloudSyncNow"),logout=document.getElementById("cloudSyncLogout");if(!detail)return;detail.textContent=session?`Angemeldet. Letzter Cloud-Stand: ${cloudLastUpdated||"noch nicht geladen"}.`:"Nicht mit der Cloud verbunden.";login.hidden=Boolean(session);now.hidden=!session;logout.hidden=!session;}
async function cloudLogin(){const email=document.getElementById("cloudSyncEmail").value.trim(),password=document.getElementById("cloudSyncPassword").value,message=document.getElementById("cloudSyncMessage");if(!email||!password){message.textContent="Bitte E-Mail und Passwort eingeben.";return;}message.textContent="Anmeldung läuft …";try{const response=await fetch(`${CLOUD_SYNC_CONFIG.url}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:CLOUD_SYNC_CONFIG.key,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)throw new Error(data.error_description||data.msg||"Anmeldung fehlgeschlagen");saveCloudSession(data);message.textContent="Anmeldung erfolgreich.";await syncCloudState({manual:true,firstLogin:true});renderCloudDialog();}catch(error){message.textContent=`Cloud-Anmeldung fehlgeschlagen: ${error.message}`;}}
function currentCloudPayload(){return {members,entries,csvArchive,roleTargets:getRoleTargets(),functionEntryEnabled:isFunctionEntryEnabled(),password:adminPassword(),sessionType,currentProbeDate,updatedBy:navigator.userAgent.slice(0,180)};}
function applyCloudPayload(data){if(!data||typeof data!=="object")return;cloudSyncApplying=true;try{if(Array.isArray(data.members)){members=data.members;safeStorage.setItem(KEYS.members,JSON.stringify(members));}if(Array.isArray(data.entries)){entries=data.entries;safeStorage.setItem(KEYS.entries,JSON.stringify(entries));}if(Array.isArray(data.csvArchive)){csvArchive=data.csvArchive;safeStorage.setItem(KEYS.archive,JSON.stringify(csvArchive));}if(data.roleTargets&&typeof data.roleTargets==="object")safeStorage.setItem(KEYS.roleTargets,JSON.stringify(data.roleTargets));if(typeof data.functionEntryEnabled==="boolean")safeStorage.setItem(KEYS.functionEntry,String(data.functionEntryEnabled));if(typeof data.password==="string"&&data.password.length>=3)safeStorage.setItem(KEYS.password,data.password);if(typeof data.sessionType==="string")sessionType=data.sessionType;if(typeof data.currentProbeDate==="string")currentProbeDate=data.currentProbeDate;renderSessionType();renderMembers();renderRoles();renderEntries();renderAdmin();renderArchive();renderStatistics();renderHistory();updateSelection();updateProbeWorkflow();}finally{cloudSyncApplying=false;}}
async function readCloudRow(){const response=await fetch(`${CLOUD_SYNC_CONFIG.url}/rest/v1/ffw_app_state?id=eq.${encodeURIComponent(CLOUD_SYNC_CONFIG.stateId)}&select=payload,updated_at`,{headers:cloudHeaders()});if(response.status===401){saveCloudSession(null);throw new Error("Cloud-Anmeldung abgelaufen");}if(!response.ok)throw new Error(`Cloud-Lesen fehlgeschlagen (${response.status})`);const rows=await response.json();return rows[0]||null;}
async function writeCloudRow(){const body={id:CLOUD_SYNC_CONFIG.stateId,payload:currentCloudPayload(),updated_at:new Date().toISOString()};const response=await fetch(`${CLOUD_SYNC_CONFIG.url}/rest/v1/ffw_app_state`,{method:"POST",headers:cloudHeaders({Prefer:"resolution=merge-duplicates,return=representation"}),body:JSON.stringify(body)});if(!response.ok)throw new Error(`Cloud-Speichern fehlgeschlagen (${response.status})`);const rows=await response.json();cloudLastUpdated=rows[0]?.updated_at||body.updated_at;}
async function syncCloudState(options={}){if(cloudSyncBusy||!cloudSession()||!navigator.onLine)return;cloudSyncBusy=true;cloudStatus("Synchronisiert …","syncing");try{const row=await readCloudRow();if(!row){await writeCloudRow();}else{const localStamp=localStorage.getItem("fw_cloud_local_updated")||"";if(!localStamp||row.updated_at>localStamp||options.firstLogin){applyCloudPayload(row.payload);cloudLastUpdated=row.updated_at;localStorage.setItem("fw_cloud_local_updated",row.updated_at);}else if(options.manual){await writeCloudRow();localStorage.setItem("fw_cloud_local_updated",cloudLastUpdated);}}cloudStatus("Cloud aktuell","online");if(options.manual&&typeof showToast==="function")showToast("Cloud-Daten wurden synchronisiert.");}catch(error){console.error(error);cloudStatus("Cloud-Fehler","error");if(options.manual&&typeof showToast==="function")showToast(error.message,"error");}finally{cloudSyncBusy=false;renderCloudDialog();}}
function scheduleCloudSync(){if(cloudSyncApplying||!cloudSession())return;localStorage.setItem("fw_cloud_local_updated",new Date().toISOString());clearTimeout(cloudSyncTimer);cloudSyncTimer=setTimeout(async()=>{if(cloudSyncBusy||!navigator.onLine)return;cloudSyncBusy=true;cloudStatus("Speichert …","syncing");try{await writeCloudRow();localStorage.setItem("fw_cloud_local_updated",cloudLastUpdated);cloudStatus("Cloud aktuell","online");}catch(error){console.error(error);cloudStatus("Cloud-Fehler","error");}finally{cloudSyncBusy=false;}},700);}
function initCloudSync(){ensureCloudSyncUi();if(cloudSession()){cloudStatus("Cloud verbindet …","syncing");syncCloudState();setInterval(()=>syncCloudState(),20000);}else cloudStatus("Cloud anmelden","offline");addEventListener("online",()=>syncCloudState());document.addEventListener("visibilitychange",()=>{if(!document.hidden)syncCloudState();});}
