let documentReportPages=[];
let documentReportReady=false;
function documentReportRequired(){return sessionType==="Ausschuss Sitzung"||(sessionType==="Allgemeine Probe"&&Boolean(currentAtueMember))||(sessionType==="Einsatz"&&Boolean(byId("opAtueUsed")?.checked));}
function documentReportKind(){return sessionType==="Ausschuss Sitzung"?"Sitzungsbericht":"Bericht Atemschutzüberwachung";}
function documentReportSubtitle(){return sessionType==="Ausschuss Sitzung"?"Formular fotografieren oder auswählen. Jede Seite wird automatisch zugeschnitten und als PDF gespeichert.":sessionType==="Einsatz"?`Einsatz-ATÜ: ${byId("opAtuePerson")?.value||"noch nicht ausgewählt"}. Formular fotografieren, prüfen und als zugeschnittenes PDF speichern.`:`ATÜ: ${currentAtueMember?nameForTile(currentAtueMember):"nicht besetzt"}. Formular fotografieren, prüfen und als zugeschnittenes PDF speichern.`;}
function ensureDocumentReportPanel(){
 let panel=byId("documentReportPanel");if(panel)return panel;
 panel=document.createElement("section");panel.id="documentReportPanel";panel.className="panel document-report-panel";panel.hidden=true;
 panel.innerHTML=`<div class="panel-heading"><span class="step yellow">DOK</span><div><h3 id="documentReportTitle">Dokumentbericht</h3><p id="documentReportSubtitle"></p></div></div><div class="document-report-actions"><label class="primary-button camera-button">Seite fotografieren<input id="documentReportCamera" type="file" accept="image/*" capture="environment" multiple></label><label class="outline-button">Bild auswählen<input id="documentReportFiles" type="file" accept="image/*" multiple></label></div><p class="document-report-help">Das Bild wird automatisch an den hellen Außenrändern zugeschnitten. Bitte das Formular möglichst gerade und vollständig fotografieren.</p><p class="document-report-status" id="documentReportStatus">Noch keine Seite aufgenommen.</p><div class="document-report-pages" id="documentReportPages"></div><div class="document-report-finish"><button class="primary-button" id="documentReportContinue" type="button">Zugeschnittenes PDF übernehmen</button></div>`;
 const target=byId("homeStageFinish")||byId("tacticsView")||byId("attendanceView");target.insertAdjacentElement("beforebegin",panel);
 const add=async files=>{for(const file of [...files]){if(!file.type.startsWith("image/"))continue;const cropped=await cropDocumentImage(file);documentReportPages.push({id:makeId(),file,blob:cropped.blob,url:URL.createObjectURL(cropped.blob),width:cropped.width,height:cropped.height,crop:cropped.crop});}documentReportReady=false;renderDocumentReportPages();};
 byId("documentReportCamera").onchange=async event=>{await add(event.target.files);event.target.value="";};
 byId("documentReportFiles").onchange=async event=>{await add(event.target.files);event.target.value="";};
 byId("documentReportPages").onclick=event=>{const button=event.target.closest("button[data-page-action]");if(!button)return;const index=documentReportPages.findIndex(page=>page.id===button.dataset.pageId);if(index<0)return;const action=button.dataset.pageAction;if(action==="delete"){URL.revokeObjectURL(documentReportPages[index].url);documentReportPages.splice(index,1);}else if(action==="up"&&index>0)[documentReportPages[index-1],documentReportPages[index]]=[documentReportPages[index],documentReportPages[index-1]];else if(action==="down"&&index<documentReportPages.length-1)[documentReportPages[index+1],documentReportPages[index]]=[documentReportPages[index],documentReportPages[index+1]];documentReportReady=false;renderDocumentReportPages();};
 byId("documentReportContinue").onclick=async()=>{if(!documentReportPages.length)return showToast("Bitte zuerst mindestens eine Seite fotografieren oder auswählen.","error");const button=byId("documentReportContinue");button.disabled=true;button.textContent="PDF wird erstellt …";try{await finalizeDocumentReportFiles();documentReportReady=true;showToast(`${documentReportKind()} wurde als zugeschnittenes PDF gespeichert.`);if(sessionType==="Einsatz"){panel.hidden=true;byId("operationReportForm")?.scrollIntoView({behavior:"smooth",block:"start"});}else openProbeTopicDialog();}catch(error){console.error(error);showToast("Das zugeschnittene PDF konnte nicht erzeugt werden.","error");}finally{button.disabled=false;button.textContent="Zugeschnittenes PDF übernehmen";}};
 return panel;
}
function showDocumentReportPanel(){const panel=ensureDocumentReportPanel();panel.hidden=false;byId("documentReportTitle").textContent=documentReportKind();byId("documentReportSubtitle").textContent=documentReportSubtitle();renderDocumentReportPages();requestAnimationFrame(()=>panel.scrollIntoView({behavior:"smooth",block:"start"}));}
function renderDocumentReportPages(){const box=byId("documentReportPages"),status=byId("documentReportStatus");if(!box||!status)return;status.textContent=documentReportPages.length?`${documentReportPages.length} Seite${documentReportPages.length===1?"":"n"} zugeschnitten. Reihenfolge bitte prüfen.`:"Noch keine Seite aufgenommen.";box.innerHTML=documentReportPages.map((page,index)=>`<article class="document-report-page"><img src="${page.url}" alt="Zugeschnittene Seite ${index+1}"><div><strong>Seite ${index+1}</strong><small>${page.width} × ${page.height} Pixel</small><span class="document-crop-badge">automatisch zugeschnitten</span></div><div class="document-report-page-actions"><button type="button" data-page-action="up" data-page-id="${page.id}" ${index===0?"disabled":""}>Nach oben</button><button type="button" data-page-action="down" data-page-id="${page.id}" ${index===documentReportPages.length-1?"disabled":""}>Nach unten</button><button type="button" class="danger-button" data-page-action="delete" data-page-id="${page.id}">Löschen</button></div></article>`).join("");}
async function cropDocumentImage(file){
 const bitmap=await createImageBitmap(file),maxSide=2400,scale=Math.min(1,maxSide/Math.max(bitmap.width,bitmap.height)),source=document.createElement("canvas");source.width=Math.max(1,Math.round(bitmap.width*scale));source.height=Math.max(1,Math.round(bitmap.height*scale));const context=source.getContext("2d",{willReadFrequently:true});context.drawImage(bitmap,0,0,source.width,source.height);bitmap.close?.();
 const sampleScale=Math.min(1,900/Math.max(source.width,source.height)),probe=document.createElement("canvas");probe.width=Math.max(1,Math.round(source.width*sampleScale));probe.height=Math.max(1,Math.round(source.height*sampleScale));const pctx=probe.getContext("2d",{willReadFrequently:true});pctx.drawImage(source,0,0,probe.width,probe.height);const data=pctx.getImageData(0,0,probe.width,probe.height).data;
 const darkCol=new Uint16Array(probe.width),darkRow=new Uint16Array(probe.height);for(let y=0;y<probe.height;y++){for(let x=0;x<probe.width;x++){const i=(y*probe.width+x)*4,luma=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2],spread=Math.max(data[i],data[i+1],data[i+2])-Math.min(data[i],data[i+1],data[i+2]);if(luma<232||spread>24){darkCol[x]++;darkRow[y]++;}}}
 const colLimit=Math.max(2,Math.round(probe.height*.012)),rowLimit=Math.max(2,Math.round(probe.width*.012));let left=0,right=probe.width-1,top=0,bottom=probe.height-1;while(left<right&&darkCol[left]<colLimit)left++;while(right>left&&darkCol[right]<colLimit)right--;while(top<bottom&&darkRow[top]<rowLimit)top++;while(bottom>top&&darkRow[bottom]<rowLimit)bottom--;
 const margin=Math.max(8,Math.round(Math.min(probe.width,probe.height)*.018));left=Math.max(0,left-margin);right=Math.min(probe.width-1,right+margin);top=Math.max(0,top-margin);bottom=Math.min(probe.height-1,bottom+margin);if((right-left)<probe.width*.45||(bottom-top)<probe.height*.45){left=0;right=probe.width-1;top=0;bottom=probe.height-1;}
 const ratio=1/sampleScale,sx=Math.round(left*ratio),sy=Math.round(top*ratio),sw=Math.min(source.width-sx,Math.round((right-left+1)*ratio)),sh=Math.min(source.height-sy,Math.round((bottom-top+1)*ratio)),out=document.createElement("canvas");out.width=sw;out.height=sh;out.getContext("2d").drawImage(source,sx,sy,sw,sh,0,0,sw,sh);const blob=await new Promise((resolve,reject)=>out.toBlob(value=>value?resolve(value):reject(new Error("Bild konnte nicht zugeschnitten werden")),"image/jpeg",.9));return {blob,width:sw,height:sh,crop:{x:sx,y:sy,width:sw,height:sh}};
}
function asciiBytes(value){return new TextEncoder().encode(value);}
function concatBytes(parts){const size=parts.reduce((sum,part)=>sum+part.length,0),out=new Uint8Array(size);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length;}return out;}
async function buildDocumentReportPdf(){const objects=[null],add=value=>(objects.push(value),objects.length-1),pagesId=add(null),pageIds=[];for(const page of documentReportPages){const bytes=new Uint8Array(await page.blob.arrayBuffer()),imageId=add(concatBytes([asciiBytes(`<< /Type /XObject /Subtype /Image /Width ${page.width} /Height ${page.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>\nstream\n`),bytes,asciiBytes("\nendstream")])),a4w=595,a4h=842,margin=18,availableW=a4w-margin*2,availableH=a4h-margin*2,ratio=Math.min(availableW/page.width,availableH/page.height),w=page.width*ratio,h=page.height*ratio,x=(a4w-w)/2,y=(a4h-h)/2,stream=`q ${w.toFixed(2)} 0 0 ${h.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm /Img Do Q`,streamBytes=asciiBytes(stream),contentId=add(concatBytes([asciiBytes(`<< /Length ${streamBytes.length} >>\nstream\n`),streamBytes,asciiBytes("\nendstream")]));pageIds.push(add(asciiBytes(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${a4w} ${a4h}] /Resources << /XObject << /Img ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`)));}objects[pagesId]=asciiBytes(`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] >>`);const catalog=add(asciiBytes(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`)),parts=[asciiBytes("%PDF-1.4\n%\xE2\xE3\xCF\xD3\n")],offsets=[0];let length=parts[0].length;for(let i=1;i<objects.length;i++){offsets[i]=length;const part=concatBytes([asciiBytes(`${i} 0 obj\n`),objects[i],asciiBytes("\nendobj\n")]);parts.push(part);length+=part.length;}const xref=length;let tail=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)tail+=String(offsets[i]).padStart(10,"0")+" 00000 n \n";tail+=`trailer\n<< /Size ${objects.length} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(asciiBytes(tail));return new Blob(parts,{type:"application/pdf"});}
async function openDocumentReportDb(){return await new Promise((resolve,reject)=>{const request=indexedDB.open("ffw-document-reports",1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("reports"))db.createObjectStore("reports",{keyPath:"id"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function saveDocumentReportRecord(record){const db=await openDocumentReportDb();await new Promise((resolve,reject)=>{const tx=db.transaction("reports","readwrite");tx.objectStore("reports").put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
async function finalizeDocumentReportFiles(){const id=`${today()}_${sessionType.replace(/\s+/g,"-")}_${Date.now()}`,safe=sessionType.replace(/\s+/g,"-"),suffix=sessionType==="Ausschuss Sitzung"?"Sitzungsbericht":"ATUE-Bericht",pdf=await buildDocumentReportPdf(),pdfName=`FFW-Wasser_${today()}_${safe}_${suffix}.pdf`;if(!(await saveBlobToSelectedFolder(pdfName,pdf)))downloadBlob(pdfName,pdf);await saveDocumentReportRecord({id,date:today(),sessionType,kind:documentReportKind(),atueMember:sessionType==="Einsatz"?(byId("opAtuePerson")?.value||""):(currentAtueMember?nameForTile(currentAtueMember):""),pageCount:documentReportPages.length,pdf,createdAt:new Date().toISOString(),processing:"auto-cropped-image-pdf"});}
async function prepareDocumentReportBeforeClose(){if(!documentReportRequired())return true;if(documentReportReady)return true;showDocumentReportPanel();showToast(`${documentReportKind()} bitte fotografieren oder auswählen.`,"error");return false;}
