let documentReportPages=[];
let documentReportReady=false;
let documentReportOcrText="";
function documentReportRequired(){return sessionType==="Ausschuss Sitzung"||(sessionType==="Allgemeine Probe"&&Boolean(currentAtueMember));}
function documentReportKind(){return sessionType==="Ausschuss Sitzung"?"Sitzungsbericht":"Bericht Atemschutzüberwachung";}
function ensureDocumentReportPanel(){
 let panel=byId("documentReportPanel");if(panel)return panel;
 panel=document.createElement("section");panel.id="documentReportPanel";panel.className="panel document-report-panel";panel.hidden=true;
 panel.innerHTML=`<div class="panel-heading"><span class="step yellow">DOK</span><div><h3 id="documentReportTitle">Dokumentbericht</h3><p id="documentReportSubtitle"></p></div></div><div class="document-report-actions"><label class="primary-button camera-button">Seite fotografieren<input id="documentReportCamera" type="file" accept="image/*" capture="environment" multiple></label><label class="outline-button">Bild auswählen<input id="documentReportFiles" type="file" accept="image/*" multiple></label><button class="outline-button" id="documentReportOcrButton" type="button">Texterkennung starten</button></div><p class="document-report-status" id="documentReportStatus">Noch keine Seite aufgenommen.</p><div class="document-report-pages" id="documentReportPages"></div><label class="document-report-text"><span>Erkannter Text, bitte mit dem Original vergleichen und korrigieren</span><textarea id="documentReportText" rows="10" placeholder="Der erkannte oder manuell übertragene Text erscheint hier."></textarea></label><div class="document-report-finish"><button class="primary-button" id="documentReportContinue" type="button">Bericht übernehmen und fortfahren</button></div>`;
 const target=byId("homeStageFinish")||byId("tacticsView")||byId("attendanceView");target.insertAdjacentElement("beforebegin",panel);
 const add=async files=>{for(const file of [...files]){if(!file.type.startsWith("image/"))continue;documentReportPages.push({file,url:URL.createObjectURL(file),name:file.name||`Seite-${documentReportPages.length+1}.jpg`});}documentReportReady=false;renderDocumentReportPages();};
 byId("documentReportCamera").addEventListener("change",e=>{add(e.target.files);e.target.value="";});
 byId("documentReportFiles").addEventListener("change",e=>{add(e.target.files);e.target.value="";});
 byId("documentReportText").addEventListener("input",e=>{documentReportOcrText=e.target.value;documentReportReady=false;});
 byId("documentReportOcrButton").addEventListener("click",runDocumentReportOcr);
 byId("documentReportContinue").addEventListener("click",async()=>{if(!documentReportPages.length)return showToast("Bitte mindestens eine Seite fotografieren oder auswählen.","error");const b=byId("documentReportContinue");b.disabled=true;b.textContent="PDF wird erzeugt …";try{await finalizeDocumentReportFiles();documentReportReady=true;showToast(`${documentReportKind()} wurde gespeichert.`);openProbeTopicDialog();}catch(error){console.error(error);showToast("Der Dokumentbericht konnte nicht erzeugt werden.","error");}finally{b.disabled=false;b.textContent="Bericht übernehmen und fortfahren";}});
 return panel;
}
function showDocumentReportPanel(){const panel=ensureDocumentReportPanel();panel.hidden=!documentReportRequired();if(panel.hidden)return;byId("documentReportTitle").textContent=documentReportKind();byId("documentReportSubtitle").textContent=sessionType==="Ausschuss Sitzung"?"Handschriftlichen Sitzungsbericht fotografieren und als Original plus durchsuchbares PDF sichern.":`ATÜ: ${currentAtueMember?nameForTile(currentAtueMember):"nicht besetzt"}. Bericht der Atemschutzüberwachung fotografieren und sichern.`;renderDocumentReportPages();requestAnimationFrame(()=>panel.scrollIntoView({behavior:"smooth",block:"start"}));}
function renderDocumentReportPages(){const box=byId("documentReportPages"),status=byId("documentReportStatus");if(!box)return;if(status)status.textContent=documentReportPages.length?`${documentReportPages.length} Seite${documentReportPages.length===1?"":"n"} aufgenommen.`:"Noch keine Seite aufgenommen.";box.innerHTML=documentReportPages.map((p,i)=>`<article><img src="${p.url}" alt="Aufgenommene Seite ${i+1}"><div><strong>Seite ${i+1}</strong><button type="button" data-doc-up="${i}" ${i===0?"disabled":""}>Nach oben</button><button type="button" data-doc-down="${i}" ${i===documentReportPages.length-1?"disabled":""}>Nach unten</button><button class="danger-button" type="button" data-doc-remove="${i}">Löschen</button></div></article>`).join("");box.querySelectorAll('[data-doc-remove]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.docRemove);URL.revokeObjectURL(documentReportPages[i].url);documentReportPages.splice(i,1);documentReportReady=false;renderDocumentReportPages();});box.querySelectorAll('[data-doc-up]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.docUp);[documentReportPages[i-1],documentReportPages[i]]=[documentReportPages[i],documentReportPages[i-1]];renderDocumentReportPages();});box.querySelectorAll('[data-doc-down]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.docDown);[documentReportPages[i+1],documentReportPages[i]]=[documentReportPages[i],documentReportPages[i+1]];renderDocumentReportPages();});}
async function loadTesseractBrowser(){if(window.Tesseract)return window.Tesseract;await new Promise((resolve,reject)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/tesseract.js@6/dist/tesseract.min.js";s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});return window.Tesseract;}
async function runDocumentReportOcr(){if(!documentReportPages.length)return showToast("Bitte zuerst mindestens eine Seite aufnehmen.","error");const button=byId("documentReportOcrButton"),status=byId("documentReportStatus");button.disabled=true;let worker;try{status.textContent="Texterkennung wird geladen …";const T=await loadTesseractBrowser();worker=await T.createWorker("deu",1,{logger:m=>{if(m.status&&typeof m.progress==="number")status.textContent=`Texterkennung: ${Math.round(m.progress*100)} %`;}});let text="";for(let i=0;i<documentReportPages.length;i++){status.textContent=`Texterkennung Seite ${i+1} von ${documentReportPages.length} …`;const result=await worker.recognize(documentReportPages[i].file);text+=`${i?"\n\n":""}--- Seite ${i+1} ---\n${result.data.text.trim()}`;}documentReportOcrText=text;byId("documentReportText").value=text;documentReportReady=false;status.textContent="Texterkennung abgeschlossen. Bitte Text mit dem Original vergleichen.";}catch(error){console.error(error);showToast("Texterkennung konnte nicht geladen werden. Der Text kann manuell eingetragen werden.","error");status.textContent="OCR nicht verfügbar. Bitte Text bei Bedarf manuell übertragen.";}finally{if(worker)await worker.terminate();button.disabled=false;}}
async function imageFileToJpeg(file){const bmp=await createImageBitmap(file);const scale=Math.min(1,1800/Math.max(bmp.width,bmp.height));const c=document.createElement("canvas");c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.drawImage(bmp,0,0,c.width,c.height);bmp.close();const blob=await new Promise(r=>c.toBlob(r,"image/jpeg",.86));return {blob,width:c.width,height:c.height};}
function asciiBytes(s){return new TextEncoder().encode(s);}
function concatBytes(parts){let n=parts.reduce((a,b)=>a+b.length,0),o=new Uint8Array(n),p=0;for(const b of parts){o.set(b,p);p+=b.length;}return o;}
function pdfEscape(s){return String(s).replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/[^\x20-\x7E]/g,ch=>({"ä":"ae","ö":"oe","ü":"ue","Ä":"Ae","Ö":"Oe","Ü":"Ue","ß":"ss"}[ch]||"?"));}
function wrapPdfText(text,max=92){const out=[];for(const para of String(text||"").split(/\n/)){let line="";for(const word of para.split(/\s+/)){if(!word)continue;if((line+" "+word).trim().length>max){out.push(line);line=word;}else line=(line+" "+word).trim();}out.push(line);}return out;}
async function buildDocumentReportPdf(){const images=[];for(const p of documentReportPages)images.push(await imageFileToJpeg(p.file));const objects=[null],add=b=>(objects.push(b),objects.length-1),pagesId=add(null),fontId=add(asciiBytes('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')),pageIds=[];for(let i=0;i<images.length;i++){const im=images[i],bytes=new Uint8Array(await im.blob.arrayBuffer()),imgId=add(concatBytes([asciiBytes(`<< /Type /XObject /Subtype /Image /Width ${im.width} /Height ${im.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>\nstream\n`),bytes,asciiBytes('\nendstream')]));const scale=Math.min(523/im.width,740/im.height),w=im.width*scale,h=im.height*scale,x=(595-w)/2,y=(842-h)/2-10,stream=`BT /F1 14 Tf 36 808 Td (${pdfEscape(documentReportKind()+" - Seite "+(i+1))}) Tj ET\nq ${w.toFixed(2)} 0 0 ${h.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm /Im${i} Do Q`;const content=asciiBytes(stream),contentId=add(asciiBytes(`<< /Length ${content.length} >>\nstream\n${stream}\nendstream`)),pageId=add(asciiBytes(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> /XObject << /Im${i} ${imgId} 0 R >> >> /Contents ${contentId} 0 R >>`));pageIds.push(pageId);}const lines=wrapPdfText(documentReportOcrText||"Kein erkannter Text vorhanden.");for(let start=0;start<lines.length;start+=46){const seg=lines.slice(start,start+46),ops=['BT /F1 15 Tf 36 806 Td (Erkannter Text - automatisch, bitte mit Original vergleichen) Tj','/F1 10 Tf 0 -24 Td'];seg.forEach((line,j)=>ops.push(`${j?'0 -15 Td ':''}(${pdfEscape(line)}) Tj`));ops.push('ET');const stream=ops.join('\n'),cid=add(asciiBytes(`<< /Length ${asciiBytes(stream).length} >>\nstream\n${stream}\nendstream`)),pid=add(asciiBytes(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${cid} 0 R >>`));pageIds.push(pid);}objects[pagesId]=asciiBytes(`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] >>`);const catalog=add(asciiBytes(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`)),parts=[asciiBytes('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n')],offsets=[0],length=parts[0].length;for(let i=1;i<objects.length;i++){offsets[i]=length;const b=concatBytes([asciiBytes(`${i} 0 obj\n`),objects[i],asciiBytes('\nendobj\n')]);parts.push(b);length+=b.length;}const xref=length;let tail=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)tail+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';tail+=`trailer\n<< /Size ${objects.length} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(asciiBytes(tail));return new Blob(parts,{type:"application/pdf"});}
async function openDocumentReportDb(){return await new Promise((resolve,reject)=>{const q=indexedDB.open("ffw-document-reports",1);q.onupgradeneeded=()=>{const db=q.result;if(!db.objectStoreNames.contains("reports"))db.createObjectStore("reports",{keyPath:"id"});};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
async function saveDocumentReportRecord(record){const db=await openDocumentReportDb();await new Promise((resolve,reject)=>{const tx=db.transaction("reports","readwrite");tx.objectStore("reports").put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
async function finalizeDocumentReportFiles(){const id=`${today()}_${sessionType.replace(/\s+/g,"-")}_${Date.now()}`,safe=sessionType.replace(/\s+/g,"-"),suffix=sessionType==="Ausschuss Sitzung"?"Sitzungsbericht":"ATUE-Bericht",pdf=await buildDocumentReportPdf(),images=[];for(let i=0;i<documentReportPages.length;i++){const converted=await imageFileToJpeg(documentReportPages[i].file);images.push(converted.blob);const name=`FFW-Wasser_${today()}_${safe}_${suffix}_Original_${String(i+1).padStart(2,"0")}.jpg`;if(!(await saveBlobToSelectedFolder(name,converted.blob)))downloadBlob(name,converted.blob);}const pdfName=`FFW-Wasser_${today()}_${safe}_${suffix}.pdf`;if(!(await saveBlobToSelectedFolder(pdfName,pdf)))downloadBlob(pdfName,pdf);await saveDocumentReportRecord({id,date:today(),sessionType,kind:documentReportKind(),atueMember:currentAtueMember?nameForTile(currentAtueMember):"",text:documentReportOcrText,images,pdf,createdAt:new Date().toISOString()});}
async function prepareDocumentReportBeforeClose(){if(!documentReportRequired())return true;if(documentReportReady)return true;showDocumentReportPanel();showToast(`${documentReportKind()} bitte fotografieren oder auswählen.`,"error");return false;}
